version: "3"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./migrations/base.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis

  bancho:
    build: .
    depends_on:
      - mysql
      - redis
    tty: true
    volumes:
      - data:/.data

  # modify this service to make it start up your own non-bancho
  # web server (for user profiles, beatmap listings, etc.). if
  # you do not have one, simply comment out or delete this.
  web:
    build: web
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  nginx:
    image: nginx
    volumes:
      - ./ext/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ${SSL_CERT_PATH}:/etc/ssl/certs/bancho.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/bancho.key:ro
      - data:/.data:ro
    ports:
      - 443:443

volumes:
  data:
