apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banchopy.fullname" . }}
type: Opaque
stringData:
  DB_USER: {{ .Values.mariadb.auth.username }}
  DB_PASS: {{ .Values.mariadb.auth.password }}
  DB_NAME: {{ .Values.mariadb.auth.database }}
  DB_PORT: {{ .Values.mariadb.auth.port | quote }}
  {{- if .Values.global.database.managed }}
  DB_HOST: {{ template "mariadb.primary.fullname" .Subcharts.mariadb }}
  {{- else }}
  DB_HOST: {{ .Values.mariadb.auth.host }}
  {{- end }}

  REDIS_USER: {{ .Values.redis.auth.username }}
  REDIS_PASS: {{ .Values.redis.auth.password }}
  REDIS_PORT: {{ .Values.redis.auth.port | quote }}
  REDIS_DB: {{ .Values.redis.auth.database | quote }}
  {{- if .Values.global.redis.managed }}
  REDIS_HOST: {{ template "common.names.fullname" .Subcharts.redis }}-master
  {{- else }}
  REDIS_HOST: {{ .Values.redis.auth.host }}
  {{- end }}

  # XXX: change your db credentials
  OSU_API_KEY: {{ .Values.osu.apiKey }}
  DATADOG_API_KEY: {{ .Values.datadog.apiKey }}
  DATADOG_APP_KEY: {{ .Values.datadog.appKey }}
